### ISSUE TITLE
Add license, think about a proper name :)

### ISSUE THREAD

**Issue by dgarijo** [tetruong/Portal2.0#1]
The apache license normally does the job. see for example https://github.com/dgarijo/Widoco/blob/master/LICENSE

The name is important for us to refer to the project. I called the previously WEXP (Workflow EXPlorer), but I didn't like it. It's up to you to find a better one :)

**Comment by nguy575** [comment]
Updated license with proper information: https://github.com/tetruong/Portal2.0/commit/469c8028e5f8f07a4315561dc1ea57ea8486f747
Final project name is still under discussion.
